version: "{build}"
platform: x64
clone_folder: c:\gopath\src\github.com\edoger\zkits-configurator
environment:
  GOPATH: c:\gopath
install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
before_test:
  - go env
  - go version
test_script:
  - go test -v -coverprofile=coverage.out -covermode=count ./...
